- name: Deploy to AWS EC2
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.HOST_DNS }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.EC2_SSH_KEY }}
    # Add if your key has a passphrase
    # passphrase: ${{ secrets.KEY_PASSPHRASE }}
    port: 22
    script: |
      echo "Navigating to application directory..."
      cd ${{ secrets.TARGET_DIR }} || exit
      echo "Pulling latest changes from master..."
      git pull origin master
      echo "Installing dependencies..."
      npm install
      echo "Building project..."
      npm run build
      echo "Restarting application..."
      pm2 restart all
